### ISSUE TITLE
Dependencies out of date, needs older TS

### ISSUE THREAD

**Issue by kylecordes** [primefaces/primeng-quickstart-cli#11]
To make this run, I had to back TypeScript down to 2.4.2:

```
    "typescript": "2.4.2"
```

and to make it run without warnings during compile, down to:

```
    "typescript": "2.3.4"
```

I suggest either updating package.json etc to make the demo work with a clean checkout. At the moment it appears some expertise with these tools is needed to minimally "off the ground" with PrimeNG.

**Comment by sudheerj** [comment]
Yes, all the quick start projects need to update with latest dependencies. I will make a try once with latest deps.

**Comment by cagataycivici** [comment]
Updated to latest at time of writing.
