### ISSUE TITLE
Cannot launch the project.

### ISSUE THREAD

**Issue by vlafargue** [primefaces/primeng-quickstart-cli#12]
Hi, I've got a problem when i try to launch the project. I've got this error message:

.../primeNgDemo/primeng-quickstart-cli/node_modules/primeng/components/progressbar/progressbar.d.ts (4,12): Cannot find name 'object'.

Is it normal ? Maybe I'am missing something

**Comment by doughaase** [comment]
Same error here.

**Comment by breynolds** [comment]
same here

**Comment by ZouZou** [comment]
Same error with me as well, did anyone get it to work?

**Comment by ZouZou** [comment]
Finally, I was able to get it to work; however I made some changes to the package.json
all the angular dependencies were changed to 5.0.5, the primeng was changed to 5.0.2, the angular/cli was changed to 1.5.5 and the typescript to 2.4.2

**Comment by cagataycivici** [comment]
@Merve7 Please update this project to latest stack asap.

**Comment by Merve7** [comment]
Updated Angular 5, PrimeNG 5 
please try new version @vlafargue @doughaase @breynolds @ZouZou

**Comment by ZouZou** [comment]
The project is working perfectly now, thank you.
