### ISSUE TITLE
Please remove generated ".js" and ".js.map" files

### ISSUE THREAD

**Issue by rkrisztian** [primefaces/primeng-quickstart-cli#4]
Hi,

The commit should not contain `*.js` and `*.js.map` files at all. Those files were generated from the `*.ts` code, and they are nothing but distraction.

[This StackOverflow page](http://stackoverflow.com/questions/24454371/typescript-how-to-keep-compiled-files-in-a-separate-directory) can help you with a better TypeScript configuration, so you can avoid such problems in the future.

Also, consider generating the project with a newer Angular CLI which incorporates the fix already.

**Comment by saad749** [comment]
+1 Please do consider this.

**Comment by cagataycivici** [comment]
I don't see any js files anymore.
